import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const playBold = localFont({
  src: "../fonts/Play-Bold.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const playRegular = localFont({
  src: "../fonts/Play-Regular.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playBold.className} ${playRegular} antialiased`}>
        {children}
      </body>
    </html>
  );
}
